# -*- coding: utf-8 -*-
"""Assemble and render the English textbook."""
import sys, os, importlib
sys.path.insert(0, "/home/user/SE/edu")
from bookE import cover, toc, render, zoo, E, read, ZOO
import srcsel, srcdocE, apidoc, bookE

Z, BY = zoo()
NF = sum(len(v) for v in Z.values())
NL = sum(f["줄"] for v in Z.values() for f in v)

# ----------------------------------------------------------------- body
def body():
    mods = [
        ("Z_found0",  ["ch_abstraction", "ch_boolean", "ch_sequential", "ch_circuits"]),
        ("A_found",   ["ch_lti", "ch_transform", "ch_sampling", "ch_prob", "ch_linalg"]),
        ("B_device",  ["ch_mos", "ch_cmos", "ch_timing", "ch_interconnect", "ch_analog"]),
        ("C_digital", ["ch_arith", "ch_control", "ch_cdc"]),
        ("D_arch",    ["ch_isa", "ch_pipeline", "ch_memory"]),
        ("E_dsp",     ["ch_filters", "ch_fft"]),
        ("F_comm",    ["ch_link", "ch_fec"]),
        ("G_rf",      ["ch_tline", "ch_radar"]),
        ("H_verif",   ["ch_verif", "ch_eda", "ch_sec"]),
        ("I_info",    ["ch_info", "ch_algebra", "ch_opt", "ch_discrete"]),
        ("J_blocks",  ["ch_memory_design", "ch_accel", "ch_noc", "ch_codec"]),
        ("K_wireless",["ch_wireless", "ch_protocol", "ch_reliability", "ch_modern"]),
        ("L_phys",    ["ch_semi", "ch_power", "ch_thermal", "ch_control"]),
        ("M_soft",    ["ch_hwsw", "ch_ml", "ch_image", "ch_measure"]),
        ("N_extra",   ["ch_async", "ch_physdes", "ch_stats", "ch_optics"]),
        ("W_practice",["ch_house", "ch_process", "ch_auto", "ch_labs",
                       "ch_papers", "ch_career", "ch_bringup", "ch_business"]),
        ("Q_more",    ["ch_queue", "ch_hls", "ch_embedded", "ch_emc"]),
        ("R_crypto",  ["ch_cryptomath", "ch_test", "ch_quantum"]),
        ("P_iface",   ["ch_mipi", "ch_pcie", "ch_gmac"]),
        ("S_iface2",  ["ch_storage", "ch_display", "ch_clocking", "ch_ipxact"]),
    ]
    out = []
    for m, fns in mods:
        mod = importlib.import_module(m)
        importlib.reload(mod)
        for f in fns:
            out.append(getattr(mod, f)())
    return "\n".join(out)


# ------------------------------------------------------- code appendix
def code_appendix():
    groups, total, log = srcsel.고르기()
    out = ['<h1 class="srcapp" id="VOL2">Volume II &mdash; Production Source Code</h1>']
    out.append(f"""<p>This volume reproduces <b>{total:,} lines</b> of source from
    {len(groups)} blocks that are shipping in silicon or sold as commercial IP. Nothing is
    paraphrased: every line is read from disk and printed with its real line number, so a
    citation of the form <code>file:line</code> anywhere in this book can be followed
    directly.</p>
    <p>Each block is preceded by four notes &mdash; <b>What</b> it is, <b>Why</b> it
    exists (what fails without it), the <b>EECS concepts</b> it rests on, and a
    <b>practice note</b> for engineers who must work with it. An <b>API dictionary</b>
    then lists every module, class, function, parameter, port, macro and typedef that the
    block declares, with the arguments each one takes, because names alone are
    ambiguous.</p>
    <div class="note">The API dictionary is generated by pattern extraction, not by a
    full language front end. It is therefore complete enough to navigate by and may miss
    unusual declarations; the verbatim source that follows each table is authoritative.</div>""")

    for name, files in groups:
        out.append(f'<h1 class="srcapp" id="blk_{abs(hash(name))%10**8}">{E(name)}</h1>')
        d = srcdocE.D.get(name)
        if d:
            out.append(f'<div class="note"><b>What this is.</b> {d["what"]}</div>')
            out.append(f'<div class="warn"><b>Why it exists.</b> {d["why"]}</div>')
            out.append(f'<div class="bs"><b>EECS concepts.</b> {d["eecs"]}</div>')
            out.append(f'<div class="ms"><b>Practice note.</b> {d["practice"]}</div>')
        else:
            raise KeyError(f"no note for bundle: {name!r}")
        tot = sum(n for _, _, n in files)
        out.append(f'<div class="kvbar">{len(files)} files &bull; {tot:,} lines</div>')

        # --- API dictionary
        for z, rel, n in files:
            try:
                kind, api = apidoc.훑기(z, rel)
            except Exception:
                continue
            if not kind:
                continue
            order = (["module", "package", "parameter", "localparam", "port",
                      "typedef", "define"] if kind == "sv"
                     else ["namespace", "class", "function", "typedef", "define"])
            tabs = [apidoc.표로(k, api.get(k, []), bookE.tab, rel)
                    for k in order if api.get(k)]
            tabs = [t for t in tabs if t]
            if tabs:
                out.append(f'<h3>API &mdash; <code>{E(rel.split("/")[-1])}</code></h3>')
                out.extend(tabs)

        # --- verbatim source
        out.append('<div class="srcwrap">')
        for i, (z, rel, n) in enumerate(files, 1):
            t = read(z, rel)
            L = t.splitlines()
            out.append(f'<h3 class="srcfile">{i}. {E(rel)} '
                       f'<span class="srcmeta">({len(L):,} lines)</span></h3>')
            out.append('<pre class="src">' + "\n".join(
                f'<span class="ln">{k:5d}</span> {E(s)}' for k, s in enumerate(L, 1))
                + '</pre>')
        out.append('</div>')
    return "\n".join(out), total


if __name__ == "__main__":
    B = body()
    C, total = code_appendix()
    meta = f"""
<p>A graduate curriculum for the design, modelling and verification of semiconductor
IP blocks, written from first principles and grounded throughout in source code that is
shipping in production silicon.</p>
<p><b>Corpus.</b> {NF:,} files, <b>{NL:,} lines</b> of real design and modelling code were
collected and indexed mechanically. Every quantity quoted in this book is computed from
that index; none is written from memory.</p>
<p><b>How to read.</b> <span style="background:#eef7f2">Green</span> boxes recall
undergraduate material; <span style="background:#f4eefa">purple</span> boxes carry
graduate-level detail and the reasoning a practising engineer needs;
<span style="background:#fbf2f2">red</span> boxes mark places where real projects have
failed.</p>"""
    full = B + C
    front = cover("EECS-IP-001", "Semiconductor IP Design",
                  "Theory, Production Code, and the Practice of a Design House",
                  meta) + toc(full)
    doc = ('<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">'
           '<title>Semiconductor IP Design</title></head><body>'
           + front + full + '</body></html>')
    render(doc, "/home/user/SE/edu/IP_Design_Textbook.pdf")
    print(f"code appendix: {total:,} lines")
